name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./frontend

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: ./frontend/package-lock.json

      - name: Set up environment variables
        run: |
          echo "VITE_API_URL=$VITE_API_URL" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Build with environment variable
        id: build
        run: VITE_API_URL=$VITE_API_URL npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ${{steps.build.outputs.download-path}}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
